### ISSUE TITLE
OutOfMemory on Android

### ISSUE THREAD

**Issue by fahad86** [AndreaVitale/av.imageview#22]
The images load great, and the module also seems to fix problems with images not loading properly sometimes.. but problem is on Android where the app seems to go out of memory very soon.

I do load a great amount of images in my app. Any suggestions on how I can overcome this?

I also have images inside scrollable view. Would it be possible not to load these images when they are not scrolled to (i.e. the module having a manual load method which I could invoke, and a creation option like autoLoad: false to prevent the initial load)?

**Comment by AndreaVitale** [comment]
The issue is not related to the module but I think that you have to rethink the app business logic.
Have a look to the "Images" paragraph [here](http://www.tidev.io/2014/03/27/memory-management/). 

```
Consider a 200px square image:

200 by 200 px image
= 40,000 pixels x 32 bits per pixel
= 1,280,000 bits
= 160,000 Bytes
= 156.25 KB
= ~1/6th MB per image in memory
```

As a best practice, do a lazy loading if you have more then 3 images and add other when needed. If you are building a Photogallery maybe a similar implementation like [this one](https://blog.laplante.io/2012/07/virtualscroller-a-titanium-module-supporting-memory-efficient-finite-and-infinite-scrolling/) could help.
