### ISSUE TITLE
Exposing cookie handling as an option. Using default user agent in requests

### ISSUE THREAD

**Issue by rlustemberg** [AndreaVitale/av.imageview#29]
In order to access cookie authenticated images, it's necessary for the http requests to include cookies. In my particular user case we also use user agent validation, which I am resetting globally using another module.
Then we could use the module as this:
```
var AVImageview =  require('av.imageview');
createImageView({
        width: 100,
        height: 100,
        image: "https://static.pexels.com/photos/27954/pexels-photo-27954.jpg",
        requestHeader: {
            'Authorization': 'Bearer your_access_token_here'
        },
handleCookies: AVImageview.HANDLE_COOKIES
    });
```
There is another issue, which is that setImage_ is invoked before the http headers are set, I'll put the image handling code in the `- (void)configurationSet` method, to make sure that al properties are set before it's invoked. I'll submit a PR later today. This solution is iOS only.I don't know if av.imageview handles sessions on Android.

**Comment by AndreaVitale** [comment]
Hi @rlustemberg thanks for your feedback. Would be great if the PR will contains also an Android solution for parity. Did you test also on Android side? I ask you 'cause the issue was opened 13days ago :-)

**Comment by rlustemberg** [comment]
One of my colleagues is working on the Android side of things. I think soon enough there will be another PR with Android parity

**Comment by AndreaVitale** [comment]
That is a really cool! Thank you @rlustemberg.

**Comment by AndreaVitale** [comment]
@rlustemberg there are any news for Android parity?

**Comment by phobeous** [comment]
Hello @AndreaVitale. I'm @rlustemberg colleague who is working on the Android parity. The user-agent HTTP header is solved by exposing the Ti.setUserAgent in Titanium SDK, which I've done in our Ti SDK fork. Once the UserAgent is set, your okHttp request via Glide takes it (actually I'm setting in Android using Java's System.setProperty("http.agent", newValue), so no modification on av.imageview module is necessary for this). Furthermore, as user-agent is set globally, all TiHTTPClient requests and even Ti's ImageView send custom user-agent header (I'll probably request a PR to Ti SDK...)

The cookie handling part is a little more complicated as TiHTTPClient class doesn't handle cookies automatically. @rlustemberg has implemented it in a very direct way, just by setting a boolean flag that indicates to handle cookies or not. I want to implement this as much similar as possible, so I'm planning to add this flag to the Android module so that, if true, it checks HTTP stored cookies and if the requested URL has the same domain and path, I'll add it using okHttp headers.

I'm working on this at the moment and will keep you posted on any progress.

PS: congrats for your great module!!

**Comment by rlustemberg** [comment]
Hi Andrea, I've just updated the iOS module so that is in full parity with the Android implementation. On my previous version the handleCookies setter was taken a system property integer, now it takes a boolean. Please feel free to test and make suggestions/merge/etc :)

**Comment by AndreaVitale** [comment]
Hi guys, I really thank you for your work. Could you please also update the README? After that I will merge the PR :-)
