### ISSUE TITLE
Support SDK 8

### ISSUE THREAD

**Issue by ffMathy** [AndreaVitale/av.imageview#69]
Would be really cool if you would support SDK 8. It is currently in Release Candidate.

**Comment by hansemannn** [comment]
It works fine here, what's your issue? The module does not need to be recompiled.

**Comment by m1ga** [comment]
only tested the Android part:
works fine here too. Just had an issue with round images in a listview where I've used `borderRadius:50%` instead of `rounded:true`. Some images only updated when I scrolled them out of the view and back in. But that was fixed with `rounded:true` and looks better :smile:

**Comment by AndreaVitale** [comment]
@ffMathy please reopen this issue if you find something that doesn't work as expected on TiSDK 8.
