### ISSUE TITLE
Problem to show some remote images

### ISSUE THREAD

**Issue by frodfigu** [AndreaVitale/av.imageview#80]
I have this code

<ImageView module="av.imageview" loadingIndicator="true" contentMode="Alloy.Globals.CONTENT_MODE_ASPECT_FILL" clipsToBound="false" top="15" height="290" width="95%" borderRadius="15" borderWidth="1" borderColor="#dbdbdb" image="{media[0].MEDIA_URL}" />

Everythings works fine but not with this image:

https://thumbor.forbes.com/thumbor/960x0/https%3A%2F%2Fblogs-images.forbes.com%2Fdavidthier%2Ffiles%2F2019%2F07%2FCapture-23.jpg

Titanium ImageViews shows well this remote image.

Thank you for your support!

**Comment by AndreaVitale** [comment]
Is due to this: https://github.com/AndreaVitale/av.imageview/blob/master/ios/Classes/AvImageviewImageView.m#L125 that is a workaround for URL with non ASCII characters.

Unescape your url and try again.

Your URL must be [https://thumbor.forbes.com/thumbor/960x0/https://blogs-images.forbes.com/davidthier/files/2019/07/Capture-23.jpg](https://thumbor.forbes.com/thumbor/960x0/https://blogs-images.forbes.com/davidthier/files/2019/07/Capture-23.jpg).
